import { DailyRecord } from "@/lib/types";

export const demoRecords: DailyRecord[] = [
  {
    id: "record-demo-2026-03-09",
    date: "2026-03-09",
    diuresis24JamMl: 900,
    tekananDarahSistolik: 128,
    tekananDarahDiastolik: 82,
    beratBadanKg: 63.4,
    exitSiteStatus: "Baik, kering, tanpa kemerahan",
    catatanHarian: "Pasien merasa nyaman. Tidak ada nyeri abdomen.",
    exchangeSessions: [
      {
        id: "exchange-demo-1",
        dailyRecordId: "record-demo-2026-03-09",
        konsentratPercent: "1.5%",
        volumeMasukMl: 2000,
        jamMasuk: "06:30",
        volumeKeluarMl: 1820,
        jamKeluar: "10:30",
        warnaCairan: "Jernih",
        catatanSesi: "Drain awal agak lambat.",
      },
      {
        id: "exchange-demo-2",
        dailyRecordId: "record-demo-2026-03-09",
        konsentratPercent: "2.5%",
        volumeMasukMl: 2000,
        jamMasuk: "11:00",
        volumeKeluarMl: 2260,
        jamKeluar: "15:00",
        warnaCairan: "Jernih kekuningan",
        catatanSesi: "",
      },
      {
        id: "exchange-demo-3",
        dailyRecordId: "record-demo-2026-03-09",
        konsentratPercent: "1.5%",
        volumeMasukMl: 2000,
        jamMasuk: "16:00",
        volumeKeluarMl: 1950,
        jamKeluar: "20:15",
        warnaCairan: "Jernih",
        catatanSesi: "Keluhan ringan pada pundak saat instilasi.",
      },
    ],
  },
  {
    id: "record-demo-2026-03-08",
    date: "2026-03-08",
    diuresis24JamMl: 1050,
    tekananDarahSistolik: 122,
    tekananDarahDiastolik: 80,
    beratBadanKg: 63.8,
    exitSiteStatus: "Sedikit kemerahan, tanpa sekret",
    catatanHarian: "Cairan tetap jernih sepanjang hari.",
    exchangeSessions: [
      {
        id: "exchange-demo-4",
        dailyRecordId: "record-demo-2026-03-08",
        konsentratPercent: "1.5%",
        volumeMasukMl: 2000,
        jamMasuk: "06:00",
        volumeKeluarMl: 1880,
        jamKeluar: "10:10",
        warnaCairan: "Jernih",
        catatanSesi: "",
      },
      {
        id: "exchange-demo-5",
        dailyRecordId: "record-demo-2026-03-08",
        konsentratPercent: "4.25%",
        volumeMasukMl: 2000,
        jamMasuk: "11:00",
        volumeKeluarMl: 2380,
        jamKeluar: "15:10",
        warnaCairan: "Jernih",
        catatanSesi: "Target ultrafiltrasi tercapai.",
      },
    ],
  },
];
