import { DailyRecord } from "@/lib/types";

export const demoRecords: DailyRecord[] = [
  {
    id: "record-demo-2026-03-09",
    date: "2026-03-09",
    diuresis24JamMl: 900,
    tekananDarahSistolik: 128,
    tekananDarahDiastolik: 82,
    beratBadanKg: 63.4,
    exitSiteStatus: "Baik, kering, tanpa kemerahan",
    catatanHarian: "Pasien merasa nyaman. Tidak ada nyeri abdomen.",
    exchangeSessions: [
      {
        id: "exchange-demo-1",
        dailyRecordId: "record-demo-2026-03-09",
        konsentratPercent: "1.5%",
        volumeMasukMl: 2000,
        jamMasukMulai: "06:30",
        jamMasukSelesai: "06:40",
        volumeKeluarMl: 2200,
        jamKeluarMulai: "10:30",
        jamKeluarSelesai: "10:45",
        warnaCairan: "Jernih",
        catatanSesi: "Drain awal agak lambat.",
      },
      {
        id: "exchange-demo-2",
        dailyRecordId: "record-demo-2026-03-09",
        konsentratPercent: "2.5%",
        volumeMasukMl: 2000,
        jamMasukMulai: "11:00",
        jamMasukSelesai: "11:10",
        volumeKeluarMl: 1900,
        jamKeluarMulai: "15:00",
        jamKeluarSelesai: "15:15",
        warnaCairan: "Jernih kekuningan",
        catatanSesi: "",
      },
      {
        id: "exchange-demo-3",
        dailyRecordId: "record-demo-2026-03-09",
        konsentratPercent: "1.5%",
        volumeMasukMl: 2000,
        jamMasukMulai: "16:00",
        jamMasukSelesai: "16:10",
        volumeKeluarMl: 2100,
        jamKeluarMulai: "20:15",
        jamKeluarSelesai: "20:30",
        warnaCairan: "Jernih",
        catatanSesi: "Keluhan ringan pada pundak saat instilasi.",
      },
    ],
  },
  {
    id: "record-demo-2026-03-08",
    date: "2026-03-08",
    diuresis24JamMl: 1050,
    tekananDarahSistolik: 122,
    tekananDarahDiastolik: 80,
    beratBadanKg: 63.8,
    exitSiteStatus: "Sedikit kemerahan, tanpa sekret",
    catatanHarian: "Cairan tetap jernih sepanjang hari.",
    exchangeSessions: [
      {
        id: "exchange-demo-4",
        dailyRecordId: "record-demo-2026-03-08",
        konsentratPercent: "1.5%",
        volumeMasukMl: 2000,
        jamMasukMulai: "06:00",
        jamMasukSelesai: "06:15",
        volumeKeluarMl: 1800,
        jamKeluarMulai: "10:10",
        jamKeluarSelesai: "10:25",
        warnaCairan: "Jernih",
        catatanSesi: "",
      },
      {
        id: "exchange-demo-5",
        dailyRecordId: "record-demo-2026-03-08",
        konsentratPercent: "4.25%",
        volumeMasukMl: 2000,
        jamMasukMulai: "11:00",
        jamMasukSelesai: "11:10",
        volumeKeluarMl: 2000,
        jamKeluarMulai: "15:10",
        jamKeluarSelesai: "15:20",
        warnaCairan: "Jernih",
        catatanSesi: "Target ultrafiltrasi tercapai.",
      },
    ],
  },
];
